[CMake] XBS build optimization
This change is a significant reworking of the LLVM build script to
utilize distribuition targets, which limit the components being built
and installed.

diff --git a/utils/buildit/build_clang b/utils/buildit/build_clang
--- a/utils/buildit/build_clang
+++ b/utils/buildit/build_clang
@@ -125,49 +125,55 @@ CMAKE_OPTS="\
 
 ################################################################################
 
-# Build the LLVM tree native.
-mkdir -p $OBJROOT/obj-llvm-native || exit 1
-cd $OBJROOT/obj-llvm-native || exit 1
+if [ "$BUILDING_HOST" != "YES" ]; then
+  # Build the LLVM tree native.
+  mkdir -p $OBJROOT/obj-llvm-native || exit 1
+  cd $OBJROOT/obj-llvm-native || exit 1
 
-# First build the native tblgen's
-OLD_SDKROOT=$SDKROOT
-OLD_TOOLCHAIN_INSTALL_DIR=$TOOLCHAIN_INSTALL_DIR
-OLD_TOOLCHAINS=$TOOLCHAINS
-OLD_IPHONEOS_DEPLOYMENT_TARGET=$IPHONEOS_DEPLOYMENT_TARGET
-OLD_TVOS_DEPLOYMENT_TARGET=$TVOS_DEPLOYMENT_TARGET
-OLD_WATCHOS_DEPLOYMENT_TARGET=$WATCHOS_DEPLOYMENT_TARGET
+  # First build the native tblgen's
+  OLD_SDKROOT=$SDKROOT
+  OLD_TOOLCHAIN_INSTALL_DIR=$TOOLCHAIN_INSTALL_DIR
+  OLD_TOOLCHAINS=$TOOLCHAINS
+  OLD_IPHONEOS_DEPLOYMENT_TARGET=$IPHONEOS_DEPLOYMENT_TARGET
+  OLD_TVOS_DEPLOYMENT_TARGET=$TVOS_DEPLOYMENT_TARGET
+  OLD_WATCHOS_DEPLOYMENT_TARGET=$WATCHOS_DEPLOYMENT_TARGET
 
-# If we're building for iOS, we need to set up a native host environment
-if [ "$RC_PURPLE" = "YES" ]; then
-  IPHONEOS_DEPLOYMENT_TARGET=
-  TVOS_DEPLOYMENT_TARGET=
-  WATCHOS_DEPLOYMENT_TARGET=
-  SDKROOT=macosx
-  TOOLCHAIN_INSTALL_DIR=
-  TOOLCHAINS=
-fi
+  # If we're building for iOS, we need to set up a native host environment
+  if [ "$RC_PURPLE" = "YES" ]; then
+    IPHONEOS_DEPLOYMENT_TARGET=
+    TVOS_DEPLOYMENT_TARGET=
+    WATCHOS_DEPLOYMENT_TARGET=
+    SDKROOT=macosx
+    TOOLCHAIN_INSTALL_DIR=
+    TOOLCHAINS=
+  fi
 
-$CMAKE -G Ninja \
-    $CMAKE_OPTS \
-    -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" \
-    -DLLVM_INCLUDE_TESTS=OFF \
-    -DLLVM_INCLUDE_EXAMPLES=OFF \
-    -DCMAKE_BUILD_TYPE=Release \
-    "$LLVM_SRCROOT" \
-    || exit 1
+  $CMAKE -G Ninja \
+      $CMAKE_OPTS \
+      -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" \
+      -DLLVM_INCLUDE_TESTS=OFF \
+      -DLLVM_INCLUDE_EXAMPLES=OFF \
+      -DCMAKE_BUILD_TYPE=Release \
+      "$LLVM_SRCROOT" \
+      || exit 1
 
-SDKROOT=$SDKROOT TOOLCHAIN_INSTALL_DIR= TOOLCHAINS= IPHONEOS_DEPLOYMENT_TARGET= TVOS_DEPLOYMENT_TARGET= WATCHOS_DEPLOYMENT_TARGET= $NINJA -v llvm-tblgen clang-tblgen llvm-config
-if [ $? != 0 ] ; then
-    echo "error: Clang 'make native tablegen exes' failed!"
-    exit 1
-fi
+  TBLGEN_OPTIONS="-DLLVM_TABLEGEN=$OBJROOT/obj-llvm-native/bin/llvm-tblgen \
+    -DCLANG_TABLEGEN=$OBJROOT/obj-llvm-native/bin/clang-tblgen"
 
-SDKROOT=$OLD_SDKROOT
-IPHONEOS_DEPLOYMENT_TARGET=$OLD_IPHONEOS_DEPLOYMENT_TARGET
-TVOS_DEPLOYMENT_TARGET=$OLD_TVOS_DEPLOYMENT_TARGET
-WATCHOS_DEPLOYMENT_TARGET=$OLD_WATCHOS_DEPLOYMENT_TARGET
-TOOLCHAIN_INSTALL_DIR=$OLD_TOOLCHAIN_INSTALL_DIR
-TOOLCHAINS=$OLD_TOOLCHAINS
+  SDKROOT=$SDKROOT TOOLCHAIN_INSTALL_DIR= TOOLCHAINS= IPHONEOS_DEPLOYMENT_TARGET= TVOS_DEPLOYMENT_TARGET= WATCHOS_DEPLOYMENT_TARGET= $NINJA -v llvm-tblgen clang-tblgen llvm-config
+  if [ $? != 0 ] ; then
+      echo "error: Clang 'make native tablegen exes' failed!"
+      exit 1
+  fi
+
+  SDKROOT=$OLD_SDKROOT
+  IPHONEOS_DEPLOYMENT_TARGET=$OLD_IPHONEOS_DEPLOYMENT_TARGET
+  TVOS_DEPLOYMENT_TARGET=$OLD_TVOS_DEPLOYMENT_TARGET
+  WATCHOS_DEPLOYMENT_TARGET=$OLD_WATCHOS_DEPLOYMENT_TARGET
+  TOOLCHAIN_INSTALL_DIR=$OLD_TOOLCHAIN_INSTALL_DIR
+  TOOLCHAINS=$OLD_TOOLCHAINS
+fi 
+
 ################################################################################
 
 # Build the LLVM tree universal.
@@ -176,7 +182,8 @@ cd $OBJROOT/obj-llvm || exit 1
 
 if [ "$BUILDING_HOST" = "YES" ]; then
   CACHE_FILE=$LLVM_SRCROOT/tools/clang/cmake/caches/Apple-stage1.cmake
-  BUILD_TARGET=stage2-install
+  BUILD_TARGET=stage2-install-distribution
+  LLVM_CONFIG_TARGET=llvm-config
 else
   CACHE_FILE=$LLVM_SRCROOT/tools/clang/cmake/caches/Apple-device.cmake
   BUILD_TARGET=install
@@ -188,8 +195,7 @@ $CMAKE -G 'Ninja' -C $CACHE_FILE \
     $CMAKE_OPTS $LLVM_REPOSITORY_FLAG $SVN_REVISION_FLAG \
     -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
     -DCMAKE_OSX_ARCHITECTURES="$HOSTS_LIST" \
-    -DLLVM_TABLEGEN=$OBJROOT/obj-llvm-native/bin/llvm-tblgen \
-    -DCLANG_TABLEGEN=$OBJROOT/obj-llvm-native/bin/clang-tblgen \
+    $TBLGEN_OPTIONS \
     -DCMAKE_INSTALL_PREFIX=$TOOLCHAIN_USR \
     -DPACKAGE_VERSION=$CLANG_VERSION \
     -DLLVM_VERSION_MAJOR=$SUBMISSION_MAJOR \
@@ -202,9 +208,6 @@ $CMAKE -G 'Ninja' -C $CACHE_FILE \
     -DBOOTSTRAP_LLVM_INCLUDE_TESTS=$INCLUDE_TESTS \
     -DBOOTSTRAP_LLVM_INCLUDE_UTILS=$INCLUDE_TESTS \
     -DBOOTSTRAP_CLANG_INCLUDE_TESTS=$INCLUDE_TESTS \
-    -DBOOTSTRAP_CLANG_TOOL_C_ARCMT_TEST_BUILD=$INCLUDE_TESTS \
-    -DBOOTSTRAP_CLANG_TOOL_C_INDEX_TEST_BUILD=$INCLUDE_TESTS \
-    -DBOOTSTRAP_CLANG_TOOL_LIBCLANG_BUILD=$INCLUDE_TESTS \
     -DBOOTSTRAP_LLVM_BUILD_RUNTIME=Off \
     $CMAKE_TOOLCHAIN_FLAGS \
     $ORDER_FILE_CMAKE_FLAG \
@@ -222,7 +225,7 @@ if [ "$BUILDING_HOST" = "YES" ]; then
   fi
 fi
 
-$NINJA -v $BUILD_TARGET
+$NINJA -v $BUILD_TARGET $LLVM_CONFIG_TARGET install-clang-headers
 if ! test $? == 0 ; then
     echo "error: LLVM 'ninja stage2-install' failed!"
     exit 1
@@ -238,7 +241,7 @@ if [ "$BUILDING_HOST" = "YES" ]; then
   $CMAKE -G 'Ninja' -C $LLVM_SRCROOT/projects/compiler-rt/cmake/caches/Apple.cmake \
       $CMAKE_OPTS \
       -DCMAKE_BUILD_TYPE=Release \
-      -DLLVM_CONFIG_PATH=$OBJROOT/obj-llvm-native/bin/llvm-config \
+      -DLLVM_CONFIG_PATH=$OBJROOT/obj-llvm/bin/llvm-config \
       -DCMAKE_INSTALL_PREFIX=$TOOLCHAIN_USR/lib/clang/$CLANG_VERSION/ \
       -DCMAKE_C_COMPILER=$TOOLCHAIN_USR/bin/clang \
       -DCMAKE_CXX_COMPILER=$TOOLCHAIN_USR/bin/clang++ \
