[CMake] Make clang_device build correctly.

diff --git a/utils/buildit/build_clang b/utils/buildit/build_clang
--- a/utils/buildit/build_clang
+++ b/utils/buildit/build_clang
@@ -33,8 +33,11 @@ else
 fi
 
 CMAKE_TOOLCHAIN_FLAGS="\
-  -DCMAKE_TOOLCHAIN_FILE=$SRCROOT/cmake/platforms/iOS.cmake \
-  -DCMAKE_SYSTEM_NAME=Darwin"
+  -DCMAKE_TOOLCHAIN_FILE=$LLVM_SRCROOT/cmake/platforms/iOS.cmake \
+  -DCMAKE_SYSTEM_NAME=Darwin \
+  -DCMAKE_OSX_DEPLOYMENT_TARGET='' \
+  -DLLVM_TOOL_LLVM_CONFIG_BUILD=Off \
+  -DLLVM_ENABLE_THREADS=Off"
 ORDER_FILE=$IB_ROOT/static-order-files/armv7/clang.order
 
 OSX=MacOSX.platform
@@ -119,9 +122,18 @@ TOOLCHAINS=$OLD_TOOLCHAINS
 mkdir -p $OBJROOT/obj-llvm || exit 1
 cd $OBJROOT/obj-llvm || exit 1
 
+if [ "$RC_PURPLE" = "YES" ]; then
+  CACHE_FILE=$LLVM_SRCROOT/tools/clang/cmake/caches/Apple-device.cmake
+  BUILD_TARGET=install
+else
+  CACHE_FILE=$LLVM_SRCROOT/tools/clang/cmake/caches/Apple-stage1.cmake
+  BUILD_TARGET=bootstrap-install
+fi
+
 TOOLCHAIN_USR=$DSTROOT/$DT_TOOLCHAIN_DIR/usr
 
-$CMAKE -G 'Ninja' -C $LLVM_SRCROOT/tools/clang/cmake/caches/Apple-stage1.cmake $CMAKE_OPTS \
+$CMAKE -G 'Ninja' -C $CACHE_FILE \
+    $CMAKE_OPTS \
     -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
     -DCMAKE_OSX_ARCHITECTURES="$HOSTS_LIST" \
     -DLLVM_TABLEGEN=$OBJROOT/obj-llvm-native/bin/llvm-tblgen \
@@ -132,59 +144,43 @@ $CMAKE -G 'Ninja' -C $LLVM_SRCROOT/tools/clang/cmake/caches/Apple-stage1.cmake $
     "$LLVM_SRCROOT" \
     || exit 1
 
-$NINJA -v bootstrap-install
+$NINJA -v $BUILD_TARGET
 if ! test $? == 0 ; then
     echo "error: LLVM 'ninja bootstrap-install' failed!"
     exit 1
 fi
 
-$NINJA -v install-libcxx
-if ! test $? == 0 ; then
-    echo "error: LLVM 'ninja install-libcxx' failed!"
-    exit 1
+if [ "$RC_PURPLE" != "YES" ]; then
+  $NINJA -v install-libcxx
+  if ! test $? == 0 ; then
+      echo "error: LLVM 'ninja install-libcxx' failed!"
+      exit 1
+  fi
 fi
 
 # Build the runtime
-mkdir -p $OBJROOT/obj-rt || exit 1
-cd $OBJROOT/obj-rt|| exit 1
+if [ "$RC_PURPLE" != "YES" ]; then
+  mkdir -p $OBJROOT/obj-rt || exit 1
+  cd $OBJROOT/obj-rt|| exit 1
 
-# First build the native tblgen's
-OLD_SDKROOT=$SDKROOT
-OLD_DT_TOOLCHAIN_DIR=$DT_TOOLCHAIN_DIR
-OLD_TOOLCHAINS=$TOOLCHAINS
-OLD_IPHONEOS_DEPLOYMENT_TARGET=$IPHONEOS_DEPLOYMENT_TARGET
-OLD_TVOS_DEPLOYMENT_TARGET=$TVOS_DEPLOYMENT_TARGET
-OLD_WATCHOS_DEPLOYMENT_TARGET=$WATCHOS_DEPLOYMENT_TARGET
 
-IPHONEOS_DEPLOYMENT_TARGET=
-TVOS_DEPLOYMENT_TARGET=
-WATCHOS_DEPLOYMENT_TARGET=
-SDKROOT=
-DT_TOOLCHAIN_DIR=
-TOOLCHAINS=
+  $CMAKE -G 'Ninja' -C $LLVM_SRCROOT/projects/compiler-rt/cmake/caches/Apple.cmake \
+      $CMAKE_OPTS \
+      -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
+      -DLLVM_CONFIG_PATH=$OBJROOT/obj-llvm-native/bin/llvm-config \
+      -DCMAKE_INSTALL_PREFIX=$TOOLCHAIN_USR/lib/clang/7.0.0/ \
+      -DCMAKE_C_COMPILER=$TOOLCHAIN_USR/bin/clang \
+      -DCMAKE_CXX_COMPILER=$TOOLCHAIN_USR/bin/clang++ \
+      "$LLVM_SRCROOT/projects/compiler-rt" \
+      || exit 1
 
-$CMAKE -G 'Ninja' -C $LLVM_SRCROOT/projects/compiler-rt/cmake/caches/Apple.cmake \
-    $CMAKE_OPTS \
-    -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
-    -DLLVM_CONFIG_PATH=$OBJROOT/obj-llvm-native/bin/llvm-config \
-    -DCMAKE_INSTALL_PREFIX=$TOOLCHAIN_USR/lib/clang/7.0.0/ \
-    -DCMAKE_C_COMPILER=$TOOLCHAIN_USR/bin/clang \
-    -DCMAKE_CXX_COMPILER=$TOOLCHAIN_USR/bin/clang++ \
-    "$LLVM_SRCROOT/projects/compiler-rt" \
-    || exit 1
+  $NINJA -v install
+  if ! test $? == 0 ; then
+      echo "error: LLVM 'ninja install (compiler-rt)' failed!"
+      exit 1
+  fi
 
-SDKROOT= DT_TOOLCHAIN_DIR= TOOLCHAINS= IPHONEOS_DEPLOYMENT_TARGET= TVOS_DEPLOYMENT_TARGET= WATCHOS_DEPLOYMENT_TARGET= $NINJA -v install
-if ! test $? == 0 ; then
-    echo "error: LLVM 'ninja install (compiler-rt)' failed!"
-    exit 1
 fi
-
-SDKROOT=$OLD_SDKROOT
-IPHONEOS_DEPLOYMENT_TARGET=$OLD_IPHONEOS_DEPLOYMENT_TARGET
-TVOS_DEPLOYMENT_TARGET=$OLD_TVOS_DEPLOYMENT_TARGET
-WATCHOS_DEPLOYMENT_TARGET=$OLD_WATCHOS_DEPLOYMENT_TARGET
-DT_TOOLCHAIN_DIR=$OLD_DT_TOOLCHAIN_DIR
-TOOLCHAINS=$OLD_TOOLCHAINS
 
 # DSTROOT fixups
 mkdir -p $TOOLCHAIN_USR/local/lib/
